### ISSUE TITLE
Anyone test flashcache in Centos7?

### ISSUE THREAD

**Issue by jimying** [facebookarchive/flashcache#209]
As the title.

**Comment by sammcj** [comment]
I don't think it's even maintained any more, the readme mentions kernel 2.6!

**Comment by jimying** [comment]
I can build and run in centos7, But I don't know if it's stable.

**Comment by maxtortime** [comment]
I builded on Centos7 once and I can make flashcache also. I should use more to know it's stable.

**Comment by richarson** [comment]
I'm using it on CentOS 7.0 through 7.2 with no problems, but it doesn't compile anymore on CentOS 7.3 with kernel-3.10.0-514.2.2.el7.x86_64, check #191 for possible progress

**Comment by pubyun** [comment]
please testing pull request 223

**Comment by Zerozlong** [comment]
I want to  use it  on CentOS 7.2 ,but i  do not know it is stable.

**Comment by anhnvname** [comment]
@pubyun it's working, I clone from your repo

**Comment by StevenLuMT** [comment]
this flashcache can install in centOS 7 with kernel 3.10.0? 
do you use this jar https://github.com/facebookarchive/flashcache/archive/3.1.2.tar.gz  ？
thanks for reply
