### ISSUE TITLE
RAID1 broken and writeback mode

### ISSUE THREAD

**Issue by dockrize** [facebookarchive/flashcache#225]
Hi,

unfortunately one SSD in my software RAID1 got broken today, i am operating flashcache in the writeback mode. 
Now i am worried that the second SSD will also break soon, according to https://github.com/facebookarchive/flashcache/issues/92 it would not be a problem if using writethrough or writearound mode.

The main problem for me is, that the SSDs cant be replaced without a server shutdown (no hotswap) and critical services are running on the server. 

**My question:** 
What would happen if the second SSD breaks also and the software RAID1 stops working? 
I cache only PIDs which are whitelisted, not everything. Now i have removed all PIDs from flashcache so it should pass the IO directly to the hard disks behind. 
According to the IO stats of the SSDs it is no longer used, so i dont believe that the SSD will break soon. But if it does - will flashcache with the writeback mode stop working or will it keep operating?

I also flushed the caching using `echo 1 > /proc/sys/dev/flashcache/$ID/do_sync`, i believe this is the correct way?

Regards!

**Comment by mohans** [comment]
I no longer work on flashcache, but :) if the second SSD crashes/breaks, you will lose data (there will be data on the SSD that is not yet been written to disk). Your best option is to do a unmount then force flashcache to sync (clean everything), then swap out the faulty SSD.

**Comment by dockrize** [comment]
Hi,

thanks a lot for your answer! I have updated my initial post previously with informations which you didnt received by mail.

> I also flushed the caching using echo 1 > /proc/sys/dev/flashcache/$ID/do_sync, i believe this is the correct way?

So there should not be datas on the SSD anymore.

Do you maybe know how flashcache would handle the IO if the second SSD goes down? Would it just pass the disk operations directly to the backend disk, or will it stop working if the mdadm raid is not available anymore? It would be great if you could tell me that or see a way without reboot or service stops. 

Unfortunately its little bit complicated to stop services which runs on the flashcache storage and i believe there is no possibility to remount the ext4 filesystem (without the cache) without reboot or service stops. 
Well, maybe its possible to remount the filesystem using the mount command. I didnt tested that. 
But i will also do some tests in a developement environment and share the results. Hopefully i find a way to keep it running without reboot :(

Regards!

**Comment by dockrize** [comment]
I made some tests, the result is:
1. It seems i cant flush the cache completely. Also it is not possible to remount the filesystem with an other device (here: the backend storage) without service shutdown. 
2. If the second SSD would fail, the flashcache mount is not accessable anymore (I/O Error).

Thereforce i dont see an option to disable flashcache at runtime. I will have to stop all services, flush the cache, and remount the file system.

**Comment by mohans** [comment]
That is accurate. You would need to stop the services, unmount the filesystem, flush everything, replace the SSD and then restart everything. If you lose the other SSD you definitely will experience data loss, because data will remain unflushed to disk.
