### ISSUE TITLE
Error on Centos 7.4 Kernel 3.10.0

### ISSUE THREAD

**Issue by PascalGasser** [facebookarchive/flashcache#228]
Hello,
I have this issue on a Centos 7.4.1708. Kernel 3.10.0-693.5.2.el7.x86_64
I have see the post #223 but it's for the 7.3 and not the 7.4.

make -C src KERNEL_TREE=/usr/src/kernels/3.10.0-693.5.2.el7.x86_64 PWD=/usr/local/src/flashcache/src all
make[1]: Entering directory `/usr/local/src/flashcache/src'
make -C /usr/src/kernels/3.10.0-693.5.2.el7.x86_64 M=/usr/local/src/flashcache/src modules V=0
make[2]: Entering directory `/usr/src/kernels/3.10.0-693.5.2.el7.x86_64'
  CC [M]  /usr/local/src/flashcache/src/flashcache_conf.o
/usr/local/src/flashcache/src/flashcache_conf.c: In function ‘flashcache_ctr’:
/usr/local/src/flashcache/src/flashcache_conf.c:1230:11: warning: passing argument 3 of ‘wait_on_bit_lock’ makes integer from pointer without a cast [enabled by default]
           flashcache_wait_schedule, TASK_UNINTERRUPTIBLE);
           ^
In file included from include/linux/mmzone.h:9:0,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/local/src/flashcache/src/flashcache_conf.c:26:
include/linux/wait.h:1147:1: note: expected ‘unsigned int’ but argument is of type ‘int (*)(void *)’
 wait_on_bit_lock(void *word, int bit, unsigned mode)
 ^
/usr/local/src/flashcache/src/flashcache_conf.c:1230:11: error: too many arguments to function ‘wait_on_bit_lock’
           flashcache_wait_schedule, TASK_UNINTERRUPTIBLE);
           ^
In file included from include/linux/mmzone.h:9:0,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/local/src/flashcache/src/flashcache_conf.c:26:
include/linux/wait.h:1147:1: note: declared here
 wait_on_bit_lock(void *word, int bit, unsigned mode)
 ^
/usr/local/src/flashcache/src/flashcache_conf.c: In function ‘flashcache_dtr’:
/usr/local/src/flashcache/src/flashcache_conf.c:1444:11: warning: passing argument 3 of ‘wait_on_bit_lock’ makes integer from pointer without a cast [enabled by default]
           TASK_UNINTERRUPTIBLE);
           ^
In file included from include/linux/mmzone.h:9:0,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/local/src/flashcache/src/flashcache_conf.c:26:
include/linux/wait.h:1147:1: note: expected ‘unsigned int’ but argument is of type ‘int (*)(void *)’
 wait_on_bit_lock(void *word, int bit, unsigned mode)
 ^
/usr/local/src/flashcache/src/flashcache_conf.c:1444:11: error: too many arguments to function ‘wait_on_bit_lock’
           TASK_UNINTERRUPTIBLE);
           ^
In file included from include/linux/mmzone.h:9:0,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/local/src/flashcache/src/flashcache_conf.c:26:
include/linux/wait.h:1147:1: note: declared here
 wait_on_bit_lock(void *word, int bit, unsigned mode)
 ^
/usr/local/src/flashcache/src/flashcache_conf.c: At top level:
/usr/local/src/flashcache/src/flashcache_conf.c:1717:2: error: unknown field ‘ioctl’ specified in initializer
  .ioctl  = flashcache_ioctl,
  ^
/usr/local/src/flashcache/src/flashcache_conf.c:1717:2: warning: initialization from incompatible pointer type [enabled by default]
/usr/local/src/flashcache/src/flashcache_conf.c:1717:2: warning: (near initialization for ‘flashcache_target.message’) [enabled by default]
/usr/local/src/flashcache/src/flashcache_conf.c: In function ‘flashcache_notify_reboot’:
/usr/local/src/flashcache/src/flashcache_conf.c:1770:11: warning: passing argument 3 of ‘wait_on_bit_lock’ makes integer from pointer without a cast [enabled by default]
           TASK_UNINTERRUPTIBLE);
           ^
In file included from include/linux/mmzone.h:9:0,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/local/src/flashcache/src/flashcache_conf.c:26:
include/linux/wait.h:1147:1: note: expected ‘unsigned int’ but argument is of type ‘int (*)(void *)’
 wait_on_bit_lock(void *word, int bit, unsigned mode)
 ^
/usr/local/src/flashcache/src/flashcache_conf.c:1770:11: error: too many arguments to function ‘wait_on_bit_lock’
           TASK_UNINTERRUPTIBLE);
           ^
In file included from include/linux/mmzone.h:9:0,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/local/src/flashcache/src/flashcache_conf.c:26:
include/linux/wait.h:1147:1: note: declared here
 wait_on_bit_lock(void *word, int bit, unsigned mode)
 ^
make[3]: *** [/usr/local/src/flashcache/src/flashcache_conf.o] Error 1
make[2]: *** [_module_/usr/local/src/flashcache/src] Error 2
make[2]: Leaving directory `/usr/src/kernels/3.10.0-693.5.2.el7.x86_64'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/usr/local/src/flashcache/src'
make: *** [all] Error 2

Tks 

Pascal

**Comment by PascalGasser** [comment]
You need to change this 4 files : 

src/flashcache_conf.c
 src/flashcache_ioctl.c
src/flashcache_ioctl.h
src/utils/flashcache_setioctl.c

With the source found in the #223

And after it work perfect with the centos 7.4 :-)

**Comment by mslovy** [comment]
The problem still exists on master branch,  anyone can fix it?
