### ISSUE TITLE
device-mapper: reload ioctl failed: Invalid argument

### ISSUE THREAD

**Issue by sneuwirth** [facebookarchive/flashcache#64]
Hi there,

I'm trying to create a cache volume on /dev/sdb by typing:
flashcache_create -p thru cachedev /dev/sda /dev/sdb

The command fails with the following error message:
device-mapper: reload ioctl failed: Invalid argument

Is there anyone who has an idea what's going wrong?

Looking forward to your help.

Thanks, Sarah

**Comment by vadimosk** [comment]
In my case the device be using by the previous bcache. You need first unregistered the device from bcache.
